### ISSUE TITLE
Страница users

### ISSUE THREAD

**Issue by Linked-su** [SimpleCabinet/SimpleCabinetFrontend#39]
Страница "Пользователи" не должна быть доступна обычным игрокам и неавторизованным.

**Comment by gravit0** [comment]
Список пользователей(и их поиск) изначально задумывался как полностью публичный. Если вы считаете что он должен быть скрыт - объясните причину

**Comment by Linked-su** [comment]
Зачем обычному игроку искать другого игрока?
Если нет то сделайте возможность давать права на просмотр страниц определленым permissions

**Comment by gravit0** [comment]
Вся информация, находящиееся в разделе "Пользователи" публичная и её может получить кто угодно. Никаких угроз безопасности это не несет. Ничего дополнительно не раскрывается. Объясните свою позицию - почему список пользователей должен быть закрытым?
Пользователь может искать кого угодно: друга, админа, грифера. Это не проблема

**Comment by Linked-su** [comment]
И по вашему обычному игроку должна быть доступна информация о балансе?
Это тоже самое что и злоумышленники имеют доступ к просмотру твоего счета в банке.

**Comment by gravit0** [comment]
Информация о балансе доступна только владельцу аккаунта и администраторам, всем остальным будет показывать 0

**Comment by Linked-su** [comment]
Тек мб убрать ее?

**Comment by gravit0** [comment]
Можно скрыть совсем если просматривает не владелец и не админ. Если это была единственная приична - можете закрывать issue

**Comment by Linked-su** [comment]
> Можно скрыть совсем если просматривает не владелец и не админ. Если это была единственная приична - можете закрывать issue

Надо так и сделать))
