### ISSUE TITLE
Добавить администраторам функцию добавлять/убавлять валюту(рубли/игровая), группу.

### ISSUE THREAD

**Issue by Linked-su** [SimpleCabinet/SimpleCabinetFrontend#41]
Добавить администраторам функцию добавлять/убавлять валюту(рубли/игровая), группу.

**Comment by gravit0** [comment]
https://github.com/SimpleCabinet/SimpleCabinetBackend/commit/bbf4c615d696c4fb2abde511b673fc1a5e87c437
Добавление группы и валюты через GUI кабинета будет позже, так как там нужно учесть аудит и использовать Order и Payment, что бы действие было видно в логах
