### ISSUE TITLE
404 Not Found при обновление страницы

### ISSUE THREAD

**Issue by Linked-su** [SimpleCabinet/SimpleCabinetFrontend#43]
После попадания на страницу лк юзера переносить на cabinet.domains.ru/user , /register , /shop и тд. Если он попытается обновить страницу ему
выдаст ошибку 404 Not Found и что бы попать обратно ему надо переходить сново на cabinet.domains.ru

**Comment by gravit0** [comment]
Правильно настройте nginx: `try_files $uri $uri/ /index.html`
