### ISSUE TITLE
Добавит кнопку для скина/плаща

### ISSUE THREAD

**Issue by Linked-su** [SimpleCabinet/SimpleCabinetFrontend#45]
Добавит кнопки для удаления плаща и скина

**Comment by gravit0** [comment]
https://github.com/SimpleCabinet/SimpleCabinetBackend/commit/d39a0eb7805a38edd5af6c6fefe76926fb987498

**Comment by gravit0** [comment]
https://github.com/SimpleCabinet/SimpleCabinetFrontend/commit/1464ab881cc85235021d84882040d89fb1094269
