### ISSUE TITLE
Добавить стандарный скин

### ISSUE THREAD

**Issue by Linked-su** [SimpleCabinet/SimpleCabinetFrontend#46]
Добавить стандартный скин после регистрации игрока

**Comment by gravit0** [comment]
Стива? Кастомный скин?
Последним коммитом было добавлено уведомление если скина нет

**Comment by Linked-su** [comment]
Обычный скин стива.
После регистрации на странице самого игрока, окно со скином пустое

**Comment by gravit0** [comment]
В последней версии добавлено сообщение что скин не установлен. Этого должно хватить
Откуда брать стандартный скин стива я не знаю. Если знаете - пишите url
Сразу скажу добаивть в репозиторий сам скин нельзя, так как он нарисован не нами

**Comment by Linked-su** [comment]
Добавить тогда возможность указать в настройках ссылку на стандартный скин

**Comment by IIIeX** [comment]
На днях попробую что-то придумать и добавить дефолтный скин.

**Comment by gravit0** [comment]
https://github.com/SimpleCabinet/SimpleCabinetFrontend/commit/1464ab881cc85235021d84882040d89fb1094269
