### ISSUE TITLE
Мульти-валютность.

### ISSUE THREAD

**Issue by SashaGoncharov19** [SimpleCabinet/SimpleCabinetFrontend#47]
Так как в кабинете имеется внутриигровая валюта, хотелось бы как-то эту валюту реализовать и на серверах. Возможно через плагин iConomy, или через любой другой плагин, чтобы вывести количество валюты на том или ином сервере. Так-же, что-бы возможно было покупать за эту валюту в магазине блоков либо где-то еще. Так-же, чтобы получать возможность зарабатывать эту валюту, например, проголосовав за проект на определенном сайте.

**Comment by gravit0** [comment]
Если сервер один или экономика общая - подключайте напрямую к таблицам ЛК.
Пополнение реализуется с помощью типа SPECIAL, из коробки можно пополить только счет внутри ЛК - который один на все сервера.
Разделите этот issue на конкретные предложения, а то у вас тут в одном месте и голосование за проект, и интеграция с экономическими плагинами, и мультивалютность ЛК. Этот issue я закрою
